### ISSUE TITLE
Launcher keeps reopening

### ISSUE THREAD

**Issue by doberdogma** [sabre230/DinoLauncher#42]
Hello, I just downloaded the Dino launcher as well as the rom for dinosaur planet. After Checking for updates and applying the patch, anytime I hit "Launch" it will not launch the game, but rather open another Dino Launcher. How do I get it to run the ROM?

**Comment by sabre230** [comment]
The launch button should ask you what program you want to open the ROM file with. In most (if not all) cases, you're going to want it to point at your N64 emulator of choice. 

If you set DinoLauncher to open your z64 file, you'll need to clear your default application for that file extension and use your emulator instead.
